### ISSUE TITLE
Understanding Differences and Benefits: Docker Container vs. esp-idf-ci-action in CI/CD

### ISSUE THREAD

**Issue by hayschan** [hfudev/esp-idf-build-and-test-ci-template#2]
Hello Hanxi Fu,

I'm currently exploring the best practices for implementing CI/CD in ESP32 projects and came across your repository "esp-idf-build-and-test-ci-template". I have also watched your [video](https://youtu.be/wxwwJR8IjAw) on Devcon. It's been incredibly helpful in understanding the CI/CD process for ESP-IDF.

I noticed that in your GitHub Action YAML, you've used the Docker container `espressif/idf` for building the target matrix:

```yaml
runs-on: ubuntu-22.04
container:
  image: espressif/idf:${{ matrix.idf-branch }}
```

I've also observed another approach used in [Uncle Rus's repository](https://github.com/UncleRus/esp-idf-lib/blob/master/.github/workflows/ci.yml), where the GitHub Action `espressif/esp-idf-ci-action` is utilized:

```yaml
- id: build_esp32
  name: Build
  uses: espressif/esp-idf-ci-action@v1
  with:
    esp_idf_version: ${{ matrix.esp_idf_version }}
    target: ${{ matrix.target }}
```

I'm keen to understand the differences and potential benefits of these two methods:

1. **Method One:** Using the Docker container `espressif/idf`.
2. **Method Two:** Using the [`espressif/esp-idf-ci-action`](https://github.com/espressif/esp-idf-ci-action).

Could you please provide insights into the following aspects:
- Performance implications (if any) of using one method over the other.
- Ease of setup and maintenance.
- Flexibility and control over the CI/CD process.
- Any specific scenarios where one method is preferred over the other.

Your insights would be incredibly valuable for the ESP32 developer community and those, like me, who are working to optimize our CI/CD pipelines.

Best regards,
Hays Chan
